src-git fantasticpackages_packages https://github.com/fantastic-packages/packages.git;master
src-git fantasticpackages_luci https://github.com/fantastic-packages/packages.git;master
src-git fantasticpackages_special https://github.com/fantastic-packages/packages.git;master
