src-get fantasticpackages_packages https://github.com/fantastic-packages/packages.git;24.10
src-get fantasticpackages_luci https://github.com/fantastic-packages/packages.git;24.10
src-get fantasticpackages_special https://github.com/fantastic-packages/packages.git;24.10
